/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as AppModuleRouteImport } from './routes/_app.$module'
import { Route as AppAdminsRouteImport } from './routes/_app.admins'
import { Route as AppAssignmentsRouteImport } from './routes/_app.assignments'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDepartmentsRouteImport } from './routes/_app.departments'
import { Route as AppExamScheduleRouteImport } from './routes/_app.exam-schedule'
import { Route as AppFacultyRouteImport } from './routes/_app.faculty'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSessionsRouteImport } from './routes/_app.sessions'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppTimetableRouteImport } from './routes/_app.timetable'
import { Route as FormTokenRouteImport } from './routes/form.$token'
import { Route as InviteResponseRouteImport } from './routes/invite.response'
import { Route as AppAdminsIndexRouteImport } from './routes/_app.admins.index'
import { Route as AppAdminsAdminIdRouteImport } from './routes/_app.admins.$adminId'
import { Route as AppAdminsAuditRouteImport } from './routes/_app.admins.audit'
import { Route as AppAdminsListRouteImport } from './routes/_app.admins.list'
import { Route as AppAdminsRolesRouteImport } from './routes/_app.admins.roles'
import { Route as AppAdminsSecurityRouteImport } from './routes/_app.admins.security'
import { Route as AppCurriculumIndexRouteImport } from './routes/_app.curriculum.index'
import { Route as AppCurriculumRegulationIdRouteImport } from './routes/_app.curriculum.$regulationId'
import { Route as AppCurriculumBatchImportRouteImport } from './routes/_app.curriculum.batch-import'
import { Route as AppCurriculumImportRouteImport } from './routes/_app.curriculum.import'
import { Route as AppCustomTimetableIdRouteImport } from './routes/_app.custom-timetable.$id'
import { Route as AppFormsIndexRouteImport } from './routes/_app.forms.index'
import { Route as AppSupportIndexRouteImport } from './routes/_app.support.index'
import { Route as AppSupportTicketIdRouteImport } from './routes/_app.support.$ticketId'
import { Route as AppUpdatesIndexRouteImport } from './routes/_app.updates.index'
import { Route as AppUpdatesCreateRouteImport } from './routes/_app.updates.create'
import { Route as AppUpdatesReleasesRouteImport } from './routes/_app.updates.releases'
import { Route as AppFormsBuilderFormIdRouteImport } from './routes/_app.forms.builder.$formId'
import { Route as AppFormsResponsesFormIdRouteImport } from './routes/_app.forms.responses.$formId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModuleRoute = AppModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminsRoute = AppAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppExamScheduleRoute = AppExamScheduleRouteImport.update({
  id: '/exam-schedule',
  path: '/exam-schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppFacultyRoute = AppFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const FormTokenRoute = FormTokenRouteImport.update({
  id: '/form/$token',
  path: '/form/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteResponseRoute = InviteResponseRouteImport.update({
  id: '/invite/response',
  path: '/invite/response',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminsIndexRoute = AppAdminsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminsRoute,
} as any)
const AppAdminsAdminIdRoute = AppAdminsAdminIdRouteImport.update({
  id: '/$adminId',
  path: '/$adminId',
  getParentRoute: () => AppAdminsRoute,
} as any)
const AppAdminsAuditRoute = AppAdminsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminsRoute,
} as any)
const AppAdminsListRoute = AppAdminsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppAdminsRoute,
} as any)
const AppAdminsRolesRoute = AppAdminsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppAdminsRoute,
} as any)
const AppAdminsSecurityRoute = AppAdminsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppAdminsRoute,
} as any)
const AppCurriculumIndexRoute = AppCurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => AppRoute,
} as any)
const AppCurriculumRegulationIdRoute =
  AppCurriculumRegulationIdRouteImport.update({
    id: '/curriculum/$regulationId',
    path: '/curriculum/$regulationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCurriculumBatchImportRoute =
  AppCurriculumBatchImportRouteImport.update({
    id: '/curriculum/batch-import',
    path: '/curriculum/batch-import',
    getParentRoute: () => AppRoute,
  } as any)
const AppCurriculumImportRoute = AppCurriculumImportRouteImport.update({
  id: '/curriculum/import',
  path: '/curriculum/import',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomTimetableIdRoute = AppCustomTimetableIdRouteImport.update({
  id: '/custom-timetable/$id',
  path: '/custom-timetable/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsIndexRoute = AppFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportIndexRoute = AppSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportTicketIdRoute = AppSupportTicketIdRouteImport.update({
  id: '/support/$ticketId',
  path: '/support/$ticketId',
  getParentRoute: () => AppRoute,
} as any)
const AppUpdatesIndexRoute = AppUpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => AppRoute,
} as any)
const AppUpdatesCreateRoute = AppUpdatesCreateRouteImport.update({
  id: '/updates/create',
  path: '/updates/create',
  getParentRoute: () => AppRoute,
} as any)
const AppUpdatesReleasesRoute = AppUpdatesReleasesRouteImport.update({
  id: '/updates/releases',
  path: '/updates/releases',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsBuilderFormIdRoute = AppFormsBuilderFormIdRouteImport.update({
  id: '/forms/builder/$formId',
  path: '/forms/builder/$formId',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsResponsesFormIdRoute = AppFormsResponsesFormIdRouteImport.update({
  id: '/forms/responses/$formId',
  path: '/forms/responses/$formId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/$module': typeof AppModuleRoute
  '/admins': typeof AppAdminsRouteWithChildren
  '/assignments': typeof AppAssignmentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/exam-schedule': typeof AppExamScheduleRoute
  '/faculty': typeof AppFacultyRoute
  '/profile': typeof AppProfileRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRoute
  '/timetable': typeof AppTimetableRoute
  '/form/$token': typeof FormTokenRoute
  '/invite/response': typeof InviteResponseRoute
  '/admins/$adminId': typeof AppAdminsAdminIdRoute
  '/admins/audit': typeof AppAdminsAuditRoute
  '/admins/list': typeof AppAdminsListRoute
  '/admins/roles': typeof AppAdminsRolesRoute
  '/admins/security': typeof AppAdminsSecurityRoute
  '/curriculum/$regulationId': typeof AppCurriculumRegulationIdRoute
  '/curriculum/batch-import': typeof AppCurriculumBatchImportRoute
  '/curriculum/import': typeof AppCurriculumImportRoute
  '/custom-timetable/$id': typeof AppCustomTimetableIdRoute
  '/support/$ticketId': typeof AppSupportTicketIdRoute
  '/updates/create': typeof AppUpdatesCreateRoute
  '/updates/releases': typeof AppUpdatesReleasesRoute
  '/admins/': typeof AppAdminsIndexRoute
  '/curriculum/': typeof AppCurriculumIndexRoute
  '/forms/': typeof AppFormsIndexRoute
  '/support/': typeof AppSupportIndexRoute
  '/updates/': typeof AppUpdatesIndexRoute
  '/forms/builder/$formId': typeof AppFormsBuilderFormIdRoute
  '/forms/responses/$formId': typeof AppFormsResponsesFormIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/$module': typeof AppModuleRoute
  '/assignments': typeof AppAssignmentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/exam-schedule': typeof AppExamScheduleRoute
  '/faculty': typeof AppFacultyRoute
  '/profile': typeof AppProfileRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRoute
  '/timetable': typeof AppTimetableRoute
  '/form/$token': typeof FormTokenRoute
  '/invite/response': typeof InviteResponseRoute
  '/admins/$adminId': typeof AppAdminsAdminIdRoute
  '/admins/audit': typeof AppAdminsAuditRoute
  '/admins/list': typeof AppAdminsListRoute
  '/admins/roles': typeof AppAdminsRolesRoute
  '/admins/security': typeof AppAdminsSecurityRoute
  '/curriculum/$regulationId': typeof AppCurriculumRegulationIdRoute
  '/curriculum/batch-import': typeof AppCurriculumBatchImportRoute
  '/curriculum/import': typeof AppCurriculumImportRoute
  '/custom-timetable/$id': typeof AppCustomTimetableIdRoute
  '/support/$ticketId': typeof AppSupportTicketIdRoute
  '/updates/create': typeof AppUpdatesCreateRoute
  '/updates/releases': typeof AppUpdatesReleasesRoute
  '/admins': typeof AppAdminsIndexRoute
  '/curriculum': typeof AppCurriculumIndexRoute
  '/forms': typeof AppFormsIndexRoute
  '/support': typeof AppSupportIndexRoute
  '/updates': typeof AppUpdatesIndexRoute
  '/forms/builder/$formId': typeof AppFormsBuilderFormIdRoute
  '/forms/responses/$formId': typeof AppFormsResponsesFormIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/download': typeof DownloadRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_app/$module': typeof AppModuleRoute
  '/_app/admins': typeof AppAdminsRouteWithChildren
  '/_app/assignments': typeof AppAssignmentsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/exam-schedule': typeof AppExamScheduleRoute
  '/_app/faculty': typeof AppFacultyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/timetable': typeof AppTimetableRoute
  '/form/$token': typeof FormTokenRoute
  '/invite/response': typeof InviteResponseRoute
  '/_app/admins/$adminId': typeof AppAdminsAdminIdRoute
  '/_app/admins/audit': typeof AppAdminsAuditRoute
  '/_app/admins/list': typeof AppAdminsListRoute
  '/_app/admins/roles': typeof AppAdminsRolesRoute
  '/_app/admins/security': typeof AppAdminsSecurityRoute
  '/_app/curriculum/$regulationId': typeof AppCurriculumRegulationIdRoute
  '/_app/curriculum/batch-import': typeof AppCurriculumBatchImportRoute
  '/_app/curriculum/import': typeof AppCurriculumImportRoute
  '/_app/custom-timetable/$id': typeof AppCustomTimetableIdRoute
  '/_app/support/$ticketId': typeof AppSupportTicketIdRoute
  '/_app/updates/create': typeof AppUpdatesCreateRoute
  '/_app/updates/releases': typeof AppUpdatesReleasesRoute
  '/_app/admins/': typeof AppAdminsIndexRoute
  '/_app/curriculum/': typeof AppCurriculumIndexRoute
  '/_app/forms/': typeof AppFormsIndexRoute
  '/_app/support/': typeof AppSupportIndexRoute
  '/_app/updates/': typeof AppUpdatesIndexRoute
  '/_app/forms/builder/$formId': typeof AppFormsBuilderFormIdRoute
  '/_app/forms/responses/$formId': typeof AppFormsResponsesFormIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/verify-otp'
    | '/$module'
    | '/admins'
    | '/assignments'
    | '/dashboard'
    | '/departments'
    | '/exam-schedule'
    | '/faculty'
    | '/profile'
    | '/sessions'
    | '/settings'
    | '/students'
    | '/timetable'
    | '/form/$token'
    | '/invite/response'
    | '/admins/$adminId'
    | '/admins/audit'
    | '/admins/list'
    | '/admins/roles'
    | '/admins/security'
    | '/curriculum/$regulationId'
    | '/curriculum/batch-import'
    | '/curriculum/import'
    | '/custom-timetable/$id'
    | '/support/$ticketId'
    | '/updates/create'
    | '/updates/releases'
    | '/admins/'
    | '/curriculum/'
    | '/forms/'
    | '/support/'
    | '/updates/'
    | '/forms/builder/$formId'
    | '/forms/responses/$formId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/verify-otp'
    | '/$module'
    | '/assignments'
    | '/dashboard'
    | '/departments'
    | '/exam-schedule'
    | '/faculty'
    | '/profile'
    | '/sessions'
    | '/settings'
    | '/students'
    | '/timetable'
    | '/form/$token'
    | '/invite/response'
    | '/admins/$adminId'
    | '/admins/audit'
    | '/admins/list'
    | '/admins/roles'
    | '/admins/security'
    | '/curriculum/$regulationId'
    | '/curriculum/batch-import'
    | '/curriculum/import'
    | '/custom-timetable/$id'
    | '/support/$ticketId'
    | '/updates/create'
    | '/updates/releases'
    | '/admins'
    | '/curriculum'
    | '/forms'
    | '/support'
    | '/updates'
    | '/forms/builder/$formId'
    | '/forms/responses/$formId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/download'
    | '/verify-otp'
    | '/_app/$module'
    | '/_app/admins'
    | '/_app/assignments'
    | '/_app/dashboard'
    | '/_app/departments'
    | '/_app/exam-schedule'
    | '/_app/faculty'
    | '/_app/profile'
    | '/_app/sessions'
    | '/_app/settings'
    | '/_app/students'
    | '/_app/timetable'
    | '/form/$token'
    | '/invite/response'
    | '/_app/admins/$adminId'
    | '/_app/admins/audit'
    | '/_app/admins/list'
    | '/_app/admins/roles'
    | '/_app/admins/security'
    | '/_app/curriculum/$regulationId'
    | '/_app/curriculum/batch-import'
    | '/_app/curriculum/import'
    | '/_app/custom-timetable/$id'
    | '/_app/support/$ticketId'
    | '/_app/updates/create'
    | '/_app/updates/releases'
    | '/_app/admins/'
    | '/_app/curriculum/'
    | '/_app/forms/'
    | '/_app/support/'
    | '/_app/updates/'
    | '/_app/forms/builder/$formId'
    | '/_app/forms/responses/$formId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  FormTokenRoute: typeof FormTokenRoute
  InviteResponseRoute: typeof InviteResponseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$module': {
      id: '/_app/$module'
      path: '/$module'
      fullPath: '/$module'
      preLoaderRoute: typeof AppModuleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admins': {
      id: '/_app/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AppAdminsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assignments': {
      id: '/_app/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exam-schedule': {
      id: '/_app/exam-schedule'
      path: '/exam-schedule'
      fullPath: '/exam-schedule'
      preLoaderRoute: typeof AppExamScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faculty': {
      id: '/_app/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof AppFacultyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable': {
      id: '/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/form/$token': {
      id: '/form/$token'
      path: '/form/$token'
      fullPath: '/form/$token'
      preLoaderRoute: typeof FormTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/response': {
      id: '/invite/response'
      path: '/invite/response'
      fullPath: '/invite/response'
      preLoaderRoute: typeof InviteResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admins/': {
      id: '/_app/admins/'
      path: '/'
      fullPath: '/admins/'
      preLoaderRoute: typeof AppAdminsIndexRouteImport
      parentRoute: typeof AppAdminsRoute
    }
    '/_app/admins/$adminId': {
      id: '/_app/admins/$adminId'
      path: '/$adminId'
      fullPath: '/admins/$adminId'
      preLoaderRoute: typeof AppAdminsAdminIdRouteImport
      parentRoute: typeof AppAdminsRoute
    }
    '/_app/admins/audit': {
      id: '/_app/admins/audit'
      path: '/audit'
      fullPath: '/admins/audit'
      preLoaderRoute: typeof AppAdminsAuditRouteImport
      parentRoute: typeof AppAdminsRoute
    }
    '/_app/admins/list': {
      id: '/_app/admins/list'
      path: '/list'
      fullPath: '/admins/list'
      preLoaderRoute: typeof AppAdminsListRouteImport
      parentRoute: typeof AppAdminsRoute
    }
    '/_app/admins/roles': {
      id: '/_app/admins/roles'
      path: '/roles'
      fullPath: '/admins/roles'
      preLoaderRoute: typeof AppAdminsRolesRouteImport
      parentRoute: typeof AppAdminsRoute
    }
    '/_app/admins/security': {
      id: '/_app/admins/security'
      path: '/security'
      fullPath: '/admins/security'
      preLoaderRoute: typeof AppAdminsSecurityRouteImport
      parentRoute: typeof AppAdminsRoute
    }
    '/_app/curriculum/': {
      id: '/_app/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof AppCurriculumIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/curriculum/$regulationId': {
      id: '/_app/curriculum/$regulationId'
      path: '/curriculum/$regulationId'
      fullPath: '/curriculum/$regulationId'
      preLoaderRoute: typeof AppCurriculumRegulationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/curriculum/batch-import': {
      id: '/_app/curriculum/batch-import'
      path: '/curriculum/batch-import'
      fullPath: '/curriculum/batch-import'
      preLoaderRoute: typeof AppCurriculumBatchImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/curriculum/import': {
      id: '/_app/curriculum/import'
      path: '/curriculum/import'
      fullPath: '/curriculum/import'
      preLoaderRoute: typeof AppCurriculumImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/custom-timetable/$id': {
      id: '/_app/custom-timetable/$id'
      path: '/custom-timetable/$id'
      fullPath: '/custom-timetable/$id'
      preLoaderRoute: typeof AppCustomTimetableIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms/': {
      id: '/_app/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof AppFormsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/': {
      id: '/_app/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof AppSupportIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/$ticketId': {
      id: '/_app/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof AppSupportTicketIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/updates/': {
      id: '/_app/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof AppUpdatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/updates/create': {
      id: '/_app/updates/create'
      path: '/updates/create'
      fullPath: '/updates/create'
      preLoaderRoute: typeof AppUpdatesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/updates/releases': {
      id: '/_app/updates/releases'
      path: '/updates/releases'
      fullPath: '/updates/releases'
      preLoaderRoute: typeof AppUpdatesReleasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms/builder/$formId': {
      id: '/_app/forms/builder/$formId'
      path: '/forms/builder/$formId'
      fullPath: '/forms/builder/$formId'
      preLoaderRoute: typeof AppFormsBuilderFormIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms/responses/$formId': {
      id: '/_app/forms/responses/$formId'
      path: '/forms/responses/$formId'
      fullPath: '/forms/responses/$formId'
      preLoaderRoute: typeof AppFormsResponsesFormIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminsRouteChildren {
  AppAdminsAdminIdRoute: typeof AppAdminsAdminIdRoute
  AppAdminsAuditRoute: typeof AppAdminsAuditRoute
  AppAdminsListRoute: typeof AppAdminsListRoute
  AppAdminsRolesRoute: typeof AppAdminsRolesRoute
  AppAdminsSecurityRoute: typeof AppAdminsSecurityRoute
  AppAdminsIndexRoute: typeof AppAdminsIndexRoute
}

const AppAdminsRouteChildren: AppAdminsRouteChildren = {
  AppAdminsAdminIdRoute: AppAdminsAdminIdRoute,
  AppAdminsAuditRoute: AppAdminsAuditRoute,
  AppAdminsListRoute: AppAdminsListRoute,
  AppAdminsRolesRoute: AppAdminsRolesRoute,
  AppAdminsSecurityRoute: AppAdminsSecurityRoute,
  AppAdminsIndexRoute: AppAdminsIndexRoute,
}

const AppAdminsRouteWithChildren = AppAdminsRoute._addFileChildren(
  AppAdminsRouteChildren,
)

interface AppRouteChildren {
  AppModuleRoute: typeof AppModuleRoute
  AppAdminsRoute: typeof AppAdminsRouteWithChildren
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppExamScheduleRoute: typeof AppExamScheduleRoute
  AppFacultyRoute: typeof AppFacultyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppCurriculumRegulationIdRoute: typeof AppCurriculumRegulationIdRoute
  AppCurriculumBatchImportRoute: typeof AppCurriculumBatchImportRoute
  AppCurriculumImportRoute: typeof AppCurriculumImportRoute
  AppCustomTimetableIdRoute: typeof AppCustomTimetableIdRoute
  AppSupportTicketIdRoute: typeof AppSupportTicketIdRoute
  AppUpdatesCreateRoute: typeof AppUpdatesCreateRoute
  AppUpdatesReleasesRoute: typeof AppUpdatesReleasesRoute
  AppCurriculumIndexRoute: typeof AppCurriculumIndexRoute
  AppFormsIndexRoute: typeof AppFormsIndexRoute
  AppSupportIndexRoute: typeof AppSupportIndexRoute
  AppUpdatesIndexRoute: typeof AppUpdatesIndexRoute
  AppFormsBuilderFormIdRoute: typeof AppFormsBuilderFormIdRoute
  AppFormsResponsesFormIdRoute: typeof AppFormsResponsesFormIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppModuleRoute: AppModuleRoute,
  AppAdminsRoute: AppAdminsRouteWithChildren,
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppExamScheduleRoute: AppExamScheduleRoute,
  AppFacultyRoute: AppFacultyRoute,
  AppProfileRoute: AppProfileRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppCurriculumRegulationIdRoute: AppCurriculumRegulationIdRoute,
  AppCurriculumBatchImportRoute: AppCurriculumBatchImportRoute,
  AppCurriculumImportRoute: AppCurriculumImportRoute,
  AppCustomTimetableIdRoute: AppCustomTimetableIdRoute,
  AppSupportTicketIdRoute: AppSupportTicketIdRoute,
  AppUpdatesCreateRoute: AppUpdatesCreateRoute,
  AppUpdatesReleasesRoute: AppUpdatesReleasesRoute,
  AppCurriculumIndexRoute: AppCurriculumIndexRoute,
  AppFormsIndexRoute: AppFormsIndexRoute,
  AppSupportIndexRoute: AppSupportIndexRoute,
  AppUpdatesIndexRoute: AppUpdatesIndexRoute,
  AppFormsBuilderFormIdRoute: AppFormsBuilderFormIdRoute,
  AppFormsResponsesFormIdRoute: AppFormsResponsesFormIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DownloadRoute: DownloadRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  FormTokenRoute: FormTokenRoute,
  InviteResponseRoute: InviteResponseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
