/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppModuleRouteImport } from './routes/_app.$module'
import { Route as AppAssignmentsRouteImport } from './routes/_app.assignments'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDepartmentsRouteImport } from './routes/_app.departments'
import { Route as AppExamScheduleRouteImport } from './routes/_app.exam-schedule'
import { Route as AppFacultyRouteImport } from './routes/_app.faculty'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSessionsRouteImport } from './routes/_app.sessions'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppTimetableRouteImport } from './routes/_app.timetable'
import { Route as AppCurriculumIndexRouteImport } from './routes/_app.curriculum.index'
import { Route as AppCurriculumRegulationIdRouteImport } from './routes/_app.curriculum.$regulationId'
import { Route as AppCurriculumBatchImportRouteImport } from './routes/_app.curriculum.batch-import'
import { Route as AppCurriculumImportRouteImport } from './routes/_app.curriculum.import'
import { Route as AppCustomTimetableIdRouteImport } from './routes/_app.custom-timetable.$id'
import { Route as AppSupportIndexRouteImport } from './routes/_app.support.index'
import { Route as AppSupportTicketIdRouteImport } from './routes/_app.support.$ticketId'
import { Route as AppUpdatesIndexRouteImport } from './routes/_app.updates.index'
import { Route as AppUpdatesCreateRouteImport } from './routes/_app.updates.create'
import { Route as AppUpdatesReleasesRouteImport } from './routes/_app.updates.releases'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModuleRoute = AppModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppExamScheduleRoute = AppExamScheduleRouteImport.update({
  id: '/exam-schedule',
  path: '/exam-schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppFacultyRoute = AppFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppCurriculumIndexRoute = AppCurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => AppRoute,
} as any)
const AppCurriculumRegulationIdRoute =
  AppCurriculumRegulationIdRouteImport.update({
    id: '/curriculum/$regulationId',
    path: '/curriculum/$regulationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCurriculumBatchImportRoute =
  AppCurriculumBatchImportRouteImport.update({
    id: '/curriculum/batch-import',
    path: '/curriculum/batch-import',
    getParentRoute: () => AppRoute,
  } as any)
const AppCurriculumImportRoute = AppCurriculumImportRouteImport.update({
  id: '/curriculum/import',
  path: '/curriculum/import',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomTimetableIdRoute = AppCustomTimetableIdRouteImport.update({
  id: '/custom-timetable/$id',
  path: '/custom-timetable/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportIndexRoute = AppSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportTicketIdRoute = AppSupportTicketIdRouteImport.update({
  id: '/support/$ticketId',
  path: '/support/$ticketId',
  getParentRoute: () => AppRoute,
} as any)
const AppUpdatesIndexRoute = AppUpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => AppRoute,
} as any)
const AppUpdatesCreateRoute = AppUpdatesCreateRouteImport.update({
  id: '/updates/create',
  path: '/updates/create',
  getParentRoute: () => AppRoute,
} as any)
const AppUpdatesReleasesRoute = AppUpdatesReleasesRouteImport.update({
  id: '/updates/releases',
  path: '/updates/releases',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$module': typeof AppModuleRoute
  '/assignments': typeof AppAssignmentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/exam-schedule': typeof AppExamScheduleRoute
  '/faculty': typeof AppFacultyRoute
  '/profile': typeof AppProfileRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRoute
  '/timetable': typeof AppTimetableRoute
  '/curriculum/$regulationId': typeof AppCurriculumRegulationIdRoute
  '/curriculum/batch-import': typeof AppCurriculumBatchImportRoute
  '/curriculum/import': typeof AppCurriculumImportRoute
  '/custom-timetable/$id': typeof AppCustomTimetableIdRoute
  '/support/$ticketId': typeof AppSupportTicketIdRoute
  '/updates/create': typeof AppUpdatesCreateRoute
  '/updates/releases': typeof AppUpdatesReleasesRoute
  '/curriculum/': typeof AppCurriculumIndexRoute
  '/support/': typeof AppSupportIndexRoute
  '/updates/': typeof AppUpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$module': typeof AppModuleRoute
  '/assignments': typeof AppAssignmentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/exam-schedule': typeof AppExamScheduleRoute
  '/faculty': typeof AppFacultyRoute
  '/profile': typeof AppProfileRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRoute
  '/timetable': typeof AppTimetableRoute
  '/curriculum/$regulationId': typeof AppCurriculumRegulationIdRoute
  '/curriculum/batch-import': typeof AppCurriculumBatchImportRoute
  '/curriculum/import': typeof AppCurriculumImportRoute
  '/custom-timetable/$id': typeof AppCustomTimetableIdRoute
  '/support/$ticketId': typeof AppSupportTicketIdRoute
  '/updates/create': typeof AppUpdatesCreateRoute
  '/updates/releases': typeof AppUpdatesReleasesRoute
  '/curriculum': typeof AppCurriculumIndexRoute
  '/support': typeof AppSupportIndexRoute
  '/updates': typeof AppUpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/$module': typeof AppModuleRoute
  '/_app/assignments': typeof AppAssignmentsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/exam-schedule': typeof AppExamScheduleRoute
  '/_app/faculty': typeof AppFacultyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/timetable': typeof AppTimetableRoute
  '/_app/curriculum/$regulationId': typeof AppCurriculumRegulationIdRoute
  '/_app/curriculum/batch-import': typeof AppCurriculumBatchImportRoute
  '/_app/curriculum/import': typeof AppCurriculumImportRoute
  '/_app/custom-timetable/$id': typeof AppCustomTimetableIdRoute
  '/_app/support/$ticketId': typeof AppSupportTicketIdRoute
  '/_app/updates/create': typeof AppUpdatesCreateRoute
  '/_app/updates/releases': typeof AppUpdatesReleasesRoute
  '/_app/curriculum/': typeof AppCurriculumIndexRoute
  '/_app/support/': typeof AppSupportIndexRoute
  '/_app/updates/': typeof AppUpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$module'
    | '/assignments'
    | '/dashboard'
    | '/departments'
    | '/exam-schedule'
    | '/faculty'
    | '/profile'
    | '/sessions'
    | '/settings'
    | '/students'
    | '/timetable'
    | '/curriculum/$regulationId'
    | '/curriculum/batch-import'
    | '/curriculum/import'
    | '/custom-timetable/$id'
    | '/support/$ticketId'
    | '/updates/create'
    | '/updates/releases'
    | '/curriculum/'
    | '/support/'
    | '/updates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$module'
    | '/assignments'
    | '/dashboard'
    | '/departments'
    | '/exam-schedule'
    | '/faculty'
    | '/profile'
    | '/sessions'
    | '/settings'
    | '/students'
    | '/timetable'
    | '/curriculum/$regulationId'
    | '/curriculum/batch-import'
    | '/curriculum/import'
    | '/custom-timetable/$id'
    | '/support/$ticketId'
    | '/updates/create'
    | '/updates/releases'
    | '/curriculum'
    | '/support'
    | '/updates'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/$module'
    | '/_app/assignments'
    | '/_app/dashboard'
    | '/_app/departments'
    | '/_app/exam-schedule'
    | '/_app/faculty'
    | '/_app/profile'
    | '/_app/sessions'
    | '/_app/settings'
    | '/_app/students'
    | '/_app/timetable'
    | '/_app/curriculum/$regulationId'
    | '/_app/curriculum/batch-import'
    | '/_app/curriculum/import'
    | '/_app/custom-timetable/$id'
    | '/_app/support/$ticketId'
    | '/_app/updates/create'
    | '/_app/updates/releases'
    | '/_app/curriculum/'
    | '/_app/support/'
    | '/_app/updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$module': {
      id: '/_app/$module'
      path: '/$module'
      fullPath: '/$module'
      preLoaderRoute: typeof AppModuleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assignments': {
      id: '/_app/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exam-schedule': {
      id: '/_app/exam-schedule'
      path: '/exam-schedule'
      fullPath: '/exam-schedule'
      preLoaderRoute: typeof AppExamScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faculty': {
      id: '/_app/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof AppFacultyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable': {
      id: '/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/curriculum/': {
      id: '/_app/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof AppCurriculumIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/curriculum/$regulationId': {
      id: '/_app/curriculum/$regulationId'
      path: '/curriculum/$regulationId'
      fullPath: '/curriculum/$regulationId'
      preLoaderRoute: typeof AppCurriculumRegulationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/curriculum/batch-import': {
      id: '/_app/curriculum/batch-import'
      path: '/curriculum/batch-import'
      fullPath: '/curriculum/batch-import'
      preLoaderRoute: typeof AppCurriculumBatchImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/curriculum/import': {
      id: '/_app/curriculum/import'
      path: '/curriculum/import'
      fullPath: '/curriculum/import'
      preLoaderRoute: typeof AppCurriculumImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/custom-timetable/$id': {
      id: '/_app/custom-timetable/$id'
      path: '/custom-timetable/$id'
      fullPath: '/custom-timetable/$id'
      preLoaderRoute: typeof AppCustomTimetableIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/': {
      id: '/_app/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof AppSupportIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/$ticketId': {
      id: '/_app/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof AppSupportTicketIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/updates/': {
      id: '/_app/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof AppUpdatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/updates/create': {
      id: '/_app/updates/create'
      path: '/updates/create'
      fullPath: '/updates/create'
      preLoaderRoute: typeof AppUpdatesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/updates/releases': {
      id: '/_app/updates/releases'
      path: '/updates/releases'
      fullPath: '/updates/releases'
      preLoaderRoute: typeof AppUpdatesReleasesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppModuleRoute: typeof AppModuleRoute
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppExamScheduleRoute: typeof AppExamScheduleRoute
  AppFacultyRoute: typeof AppFacultyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppCurriculumRegulationIdRoute: typeof AppCurriculumRegulationIdRoute
  AppCurriculumBatchImportRoute: typeof AppCurriculumBatchImportRoute
  AppCurriculumImportRoute: typeof AppCurriculumImportRoute
  AppCustomTimetableIdRoute: typeof AppCustomTimetableIdRoute
  AppSupportTicketIdRoute: typeof AppSupportTicketIdRoute
  AppUpdatesCreateRoute: typeof AppUpdatesCreateRoute
  AppUpdatesReleasesRoute: typeof AppUpdatesReleasesRoute
  AppCurriculumIndexRoute: typeof AppCurriculumIndexRoute
  AppSupportIndexRoute: typeof AppSupportIndexRoute
  AppUpdatesIndexRoute: typeof AppUpdatesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppModuleRoute: AppModuleRoute,
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppExamScheduleRoute: AppExamScheduleRoute,
  AppFacultyRoute: AppFacultyRoute,
  AppProfileRoute: AppProfileRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppCurriculumRegulationIdRoute: AppCurriculumRegulationIdRoute,
  AppCurriculumBatchImportRoute: AppCurriculumBatchImportRoute,
  AppCurriculumImportRoute: AppCurriculumImportRoute,
  AppCustomTimetableIdRoute: AppCustomTimetableIdRoute,
  AppSupportTicketIdRoute: AppSupportTicketIdRoute,
  AppUpdatesCreateRoute: AppUpdatesCreateRoute,
  AppUpdatesReleasesRoute: AppUpdatesReleasesRoute,
  AppCurriculumIndexRoute: AppCurriculumIndexRoute,
  AppSupportIndexRoute: AppSupportIndexRoute,
  AppUpdatesIndexRoute: AppUpdatesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
