org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true
android.useAndroidX=true
kotlin.jvm.target.validation.mode=ignore
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.vfs.watch=true
