// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTegv3BzW9RTiuZcy-5-ElcUVMtG5IZEk',
    appId: '1:1144756968:web:6dc2d5ec3256f4fe5a075d',
    messagingSenderId: '1144756968',
    projectId: 'campusly-app-2026',
    authDomain: 'campusly-app-2026.firebaseapp.com',
    storageBucket: 'campusly-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqu2mmonaDncF6lM3bHEUiCZXA_Mt1ZKY',
    appId: '1:1144756968:android:296f3cef7a3277b05a075d',
    messagingSenderId: '1144756968',
    projectId: 'campusly-app-2026',
    storageBucket: 'campusly-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd5BmxsIkt9s-mpcooa0Foj8fIeQrbKOE',
    appId: '1:1144756968:ios:99e8bc89848a2cc15a075d',
    messagingSenderId: '1144756968',
    projectId: 'campusly-app-2026',
    storageBucket: 'campusly-app-2026.firebasestorage.app',
    iosBundleId: 'com.campusly.campusly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd5BmxsIkt9s-mpcooa0Foj8fIeQrbKOE',
    appId: '1:1144756968:ios:99e8bc89848a2cc15a075d',
    messagingSenderId: '1144756968',
    projectId: 'campusly-app-2026',
    storageBucket: 'campusly-app-2026.firebasestorage.app',
    iosBundleId: 'com.campusly.campusly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTegv3BzW9RTiuZcy-5-ElcUVMtG5IZEk',
    appId: '1:1144756968:web:1f21bbfe9e7c0aaa5a075d',
    messagingSenderId: '1144756968',
    projectId: 'campusly-app-2026',
    authDomain: 'campusly-app-2026.firebaseapp.com',
    storageBucket: 'campusly-app-2026.firebasestorage.app',
  );
}
